### ISSUE TITLE
Item Tracks only play for GMs

### ISSUE THREAD

**Issue by ChromeWisp** [death-save/maestro#102]
**Describe the bug**
The sound of an item track can only be heard when a GM uses the item, and cannot be heard as a player using the item.

**To Reproduce**
1. Join a world as GM
2. Enable Item Track in Configure Settings > Module Settings
3. Add a sound to the playlists
4. Create an actor and assign it to another player in permissions, then add a new item for the actor
5. Edit the actor's item, click Item Track, set the playlist to the one containing your sound and the track to be that sound
6. As the GM, use the actor's item, thus playing the Item Track audibly
7. Log out and back in as the actor's player and use the actor's item, **not hearing the item track played**

**Expected behavior**
Any player would be able to hear an Item Track set to a used item.

**Foundry Setup (please complete the following information):**
 - OS: Windows 10
 - Browser: Foundry client
 - Foundry Version 0.7.9
 - Maestro Version 0.7.2

**Comment by eclarke12** [comment]
@ChromeWisp do you get any errors in the player's console (F12 for Windows/most browsers) when you try to play the item track?

**Comment by ChromeWisp** [comment]
It doesn't seem like there are any... This is what I get in console when I use the item:
![consolelog](https://user-images.githubusercontent.com/4585257/105638925-1991d080-5e3b-11eb-8ce2-87f90237657a.png)

**Comment by ChromeWisp** [comment]
I should mention, I'm using the Lancer system here, but the issue happens with D&D 5e too so I wasn't sure if that's a factor.

**Comment by eclarke12** [comment]
The issue is that item tracks will not play when no GM is logged in. I will investigate this, but for now the workaround is to ensure a GM is logged in if you want all users to hear the sound.

**Comment by The-Grison** [comment]
I am experiencing this issue as well. My GM account can hear item tracks, but my test player account cannot -- even when both accounts are simultaneously connected to the same world (via different browsers).

**Comment by eclarke12** [comment]
Having a GM logged in is now set as a requirement for module functionality.
