### ISSUE TITLE
BUG: Can't install Maestro. not a valid manifest file

### ISSUE THREAD

**Issue by Jonwh25** [death-save/maestro#104]
Can't install Maestro from foundry install.

![image](https://user-images.githubusercontent.com/60674327/106402048-80cff780-63dc-11eb-9392-883aa6057be6.png)

**Comment by eclarke12** [comment]
Build process failed...
Can you check again?

**Comment by Jonwh25** [comment]
confirmed. It is now fixed. Thanks
