### ISSUE TITLE
Suggestion: Multiple Playlists on scene-activation

### ISSUE THREAD

**Issue by Hebelios** [death-save/maestro#106]
**What?**
Add the possibility to play not just _one_ but multiple chosen playlists on activation when configuring a scene.

**Why?**
I want scenes to have a variety of randomized songs play in the background - but also wish for global atmospheric music (e.g. forest-atmosphere) to play via playlists rather than placing the same track on battlemaps with max-radius, change type to global (if it's a youtube track in combination with bellows you'll have to look that up as well too!). Lots of unneccessary work!
The way playlists work right now you have to choose between simultaneous or random playback.

By defining multiple playlists to play on activation you can have a playlist "Forest Music" which plays randomized songs and a playlist "Forest Ambience" which play simultaneous atmosphere. If needed you could also add special occasion atmosphere like "Fire Ambience" on top of the scene that requires it. It will make the option highly configurable, helping DMs prepare sessions ahead of time.
You won't have to place each atmospheric forest on the map by hand nor do you have to remind yourself to play the other playlist mid-session.

**How?**
Preferably by adding a kind of '+' button to the end of the Audio Playlist option in the scene-configuration. 
Clicking it will create a new line to add an additional playlist.

**Describe alternatives you've considered**
One might also try to add a kind of button to tracks in playlists themselves to specify whether they should play simultaneously as well, overriding the playlists general instruction to go single-random instead.

**Comment by eclarke12** [comment]
Since core took on Maestro's scene tracks I consider this feature deprecated and won't be working on it. I suggest opening an issue on the official Foundry tracker: https://gitlab.com/foundrynet/foundryvtt/-/issues/
