### ISSUE TITLE
foundry.js:2499 TypeError: Cannot read property '_id' of undefined at Module._onPreUpdatePlaylistSound

### ISSUE THREAD

**Issue by mvanduijvenvoorde** [death-save/maestro#107]
**Describe the bug**
I get errors in the console.log when playing a playlist after the last maestro update. The music does play though and I do not see any detrimental behaviors in FoundryVTT at the moment.

**To Reproduce**
1. Go to Playlists
2. Click on a Playlist
3. Play the playlist
3. See error

**Expected behavior**
No error in the console.log

**Screenshots**
Added

**Foundry Setup (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 
 - Foundry Version: 0.7.9
 - Maestro Version 0.7.3

**Additional context**
ERROR:
````
foundry.js:2499 TypeError: Cannot read property '_id' of undefined
    at Module._onPreUpdatePlaylistSound (misc.js:192)
    at maestro.js:124
    at Function._call (foundry.js:2496)
    at Function.call (foundry.js:2481)
    at foundry.js:29991
    at Array.reduce (<anonymous>)
    at Playlist.updateEmbeddedEntity (foundry.js:29978)
    at PlaylistDirectory._onSoundToggleMode (foundry.js:27555)
    at HTMLAnchorElement.<anonymous> (foundry.js:27330)
    at HTMLElement.dispatch (jquery.min.js:2)
````

**Comment by mvanduijvenvoorde** [comment]
![maestro_foundry_error](https://user-images.githubusercontent.com/70683364/106425138-b23fd600-6463-11eb-9acd-dca4baff453f.png)

**Comment by eclarke12** [comment]
I wasn't able to repro this behaviour, but I've fixed the possible cause in the faulting module
