### ISSUE TITLE
Playback of HypeTrack throws error in console.

### ISSUE THREAD

**Issue by Tupsi** [death-save/maestro#111]
**Describe the bug**
Whenever a sound is played from the HypeTrack feature (its the actors turn in combat), the following error shows up in console (sound plays nicely though).

hype-track.js:83 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at HypeTrack._processHype (hype-track.js:83)

**To Reproduce**
1. Enter Track under the Hype Playlist
2. Assign this track to an actor
3. start combat and fast forward to that actor
4. hear sound and see console error.

**Expected behavior**
Sounds without an error in the console.

**Screenshots**
N/A

**Foundry Setup (please complete the following information):**
 - OS: linux
 - Browser chrome and edge
 - Foundry Version 0.7.9
 - Maestro Version 0.7.4

**Additional context**
N/A

**Comment by eclarke12** [comment]
This should be resolved. Please check out the upcoming 0.7.6 and reopen if still occurring.
