### ISSUE TITLE
Multiple Hype songs playing at the same time

### ISSUE THREAD

**Issue by drcrowswildride** [death-save/maestro#113]
**Describe the bug**
After multiple rounds of combat, multiple hype tracks will start playing at once. The hype track will not say that other songs are playing, and you cannot turn them off without refreshing the entire page. Occasionally, the combat music will begin playing at the same time as one or both hype songs. 

**To Reproduce**
1. Have multiple combatants in an encounter.
2. Have 5 actors have hype songs and 5 other actors have no hype music with combat music playing in the background.
3. The pause combat music should be toggled on while attempting this.
4. Have them go through multiple rounds of combat. 

**Expected behavior**
One player's hype music should continue to do play when you move to the next player's turn. The next player's hype music will also begin to play. The first player's music will show that it is not playing, but you can hear it. Sometimes, the combat music will begin to play at the same time as the two hype songs. 

**Foundry Setup (please complete the following information):**
 - Browser: Firefox
 - Foundry Version [e.g. 0.7.9]
 - DnD5e - 5e system [e.g. 1.2.4]
 - Maestro Version [e.g. 0.7.4])

**Comment by eclarke12** [comment]
I believe this was resolved in 0.7.5. Please check out the upcoming 0.7.6 release for FVTT 0.8.9 and reopen if this issue is still occurring.
