### ISSUE TITLE
Add support for Call of Cthulhu 7th Ed system

### ISSUE THREAD

**Issue by dragaobanguela** [death-save/maestro#119]
**Describe the bug**
Dunno if it's a bug, or just the module specific for D&D, but the item track won't work on CoC/DG systems when clicked in the item in the character sheet (the system which has a discord chat on Foundry discord, "Chaosium", the "official" one). It would be very nice to implement it, since CoC is very popular, after D&D (and is very neat to have a pistol sound like a pistol lol).

**To Reproduce**
1. Install system Call of Cthulhu 7ed Unofficial by [HavelockV](https://foundryvtt.com/packages/CoC7/)
2. Click on Create Item
3. Scroll down to Item Track
4. Weapon don't activate the Track on Item Track playlist

**Expected behavior**
Clicking in the Weapon and activating the Item Track playlist.

**Screenshots**
![revolver](https://user-images.githubusercontent.com/84280649/118402215-575f7280-b63f-11eb-8593-458b31bb217b.png)

**Foundry Setup (please complete the following information):**
 - OS: Windows 10
 - Foundry Version 0.7.9
 - Maestro Version last version

**Comment by BabyfaceFinlayson** [comment]
Same issue here on Mac OS, with 7.9. Would very much welcome a fix.

**Comment by eclarke12** [comment]
This appears to be mostly resolved in 0.7.6 please see https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/issues/257 for some additional info
