### ISSUE TITLE
Hype and Item Tracks don't work after Foundry update 0.8.6

### ISSUE THREAD

**Issue by maxphoenix01** [death-save/maestro#120]
After I updated Foundry to Version 0.8.6, the hype tracks and item tracks for characters don't work at all. Even though they are still set correctly.

**Comment by bibicvc** [comment]
I found the same bug -to provide some information on reproducibility, here is what I find works and doesn't work:

What Works: 
Item tracks referencing a particular sound on on a prototype token or a linked token

What doesn't work:
Item tracks referencing a random sound from a playlist 
Item tracks referencing a particular sound on an unlinked token

**Comment by TheMOELANDER** [comment]
Found the same problem. Still worked in 0.7.10, not anymore in 0.8.6

**Comment by welovekah** [comment]
Same issue in 0.8.6

**Comment by Nuku** [comment]
Same issue, same version.

**Comment by krobibero** [comment]
Same. Just updated today on a test server. Yep, not working after 0.8.6.

**Comment by g1eagle** [comment]
I found the same bug on freshly updated install.
