### ISSUE TITLE
Simple UI improvement: focus on 2nd tab if combat tracker has entries

### ISSUE THREAD

**Issue by apoapostolov** [death-save/maestro#123]
Currently, when there is no combat, Maestro icon in Combat Tracker shows only Default Track. This is all good.

However, when there are combatants in tracker before combat and when combat has started, opening Maestro icon in Combat Tracker will result in two tabs, however focus is on the first tab (defaults). Instead, it should be focus on second tab (this combat). Usually in such scenarios changes need to be made in this combat, not to the default. 

If possible, either focus on current combat tab (2nd tab) or add the current combat tab as first and the default track as 2nd.

**Comment by eclarke12** [comment]
implemented in 0.7.6
