### ISSUE TITLE
When Combat Ends, End Hype Tracks

### ISSUE THREAD

**Issue by Nuku** [death-save/maestro#129]
Currently, if a hype track is going and combat ends, it continues.

Ideally, when you end combat, all things relating to ending a turn should trigger, which would end the song, and resume other noises if they were being quieted.

**Comment by eclarke12** [comment]
Fixed in upcoming release

**Comment by Nuku** [comment]
Woo! Thank you.

**Comment by eclarke12** [comment]
Duplicate of #36
