### ISSUE TITLE
2 Song play at the same time

### ISSUE THREAD

**Issue by rinnocenti** [death-save/maestro#130]
**Describe the bug**
When starting an encounter it has a default playlist for combat music.
The character who initiates the initiative rolls has a Hype song, the combat music and the Hype song play at the same time.

**To Reproduce**
- creates a fight (with random music when starting the fight)
- Put 3 fighters (two of them with different hype songs).
If the player who initiates initiative rolls is the fighter with a hype song, the combat music and hype will play at the same time.

**Expected behavior**
The ambient music on the map pauses and switches to combat music.
If the first combatant is a combatant with a hypsong, they must stop the default combat song and start the hypesong

**Screenshots**

**Foundry Setup (please complete the following information):**
 - OS: Win 10
 - Browser : chrome
 - Foundry Version 0.8.8
 - Maestro Version 0.7.5

**Additional context**
other errors also happen, as if the combat ends and a hypesong is playing and it doesn't stop and the other songs don't return.

a lot of this is probably due to Foundry's default behavior that by default allows songs from different playlists to always play together.

**Comment by eclarke12** [comment]
Hype tracks now pause the combat track
