### ISSUE TITLE
Item tracks won't play when using Midi-qol

### ISSUE THREAD

**Issue by Drudok** [death-save/maestro#131]
Item tracks won't play when using Midi-qol in the latest update. Can confirm it was working in Foundry 0.7.x with similar Midi-qol settings 
Switching off Midi-qol fixes the problem immediately

Console outputs when attacking:
`Uncaught (in promise) TypeError: Cannot read property 'actor' of undefined
    at ItemTrack.chatMessageHandler (item-track.js:69)
    at maestro.js:180
    at Function._call (eval at <anonymous> (listeners.js:56), <anonymous>:4:14)
    at Function.call (foundry.js:179)
    at ChatMessage.getHTML (foundry.js:12982)
    at async ChatLog.updateMessage (foundry.js:32398)`

 - OS: It’s running in a docker container using foundryvtt-docker 
 - Browser Doesn't work on Chrome and Edge
 - Foundry Version 0.8.8 
 - 5e System Version 1.3.6
 - Maestro Version 0.7.5
 - Midi-qol version 0.8.33

**Comment by bibicvc** [comment]
I can confirm the same bug. 

There is a workaround - the item track will play if you play it directly from an item in the character sheet of a prototype token so long as that token is not placed anywhere on the current scene. If the token is present in the scene and you try playing the sound from either the character sheet of the placed token or the prototype token, it will no longer work.

**Comment by susscribe** [comment]
works fine in fvtt 0.8.8 with latest dnd5e, midi and maestro

**Comment by maxphoenix01** [comment]
Can confirm having the same problem. Made a completely new playlist and tried adding the item track to it but the issue persists. Also using Midi QOL. Worked fine in the previous update.

**Comment by franckflo** [comment]
I confirm having the same issue.

**Comment by DrewStremer** [comment]
Hello All, I can also confirm having the same issue. Below is what I found on the MidiQoL GitHub:

Maestro looks for the attack roll chat card in the chat log to play its critical/attack/fumble sounds. If you are using the merge card then the attack roll card is never created and Maestro can't play its sounds. You can use the midi-qol custom sounds instead.

**Comment by cogito808** [comment]
I tried changing that setting and disabling all Midi QOL sounds and still getting the same error.

> Maestro looks for the attack roll chat card in the chat log to play its critical/attack/fumble sounds. If you are using the merge card then the attack roll card is never created and Maestro can't play its sounds. You can use the midi-qol custom sounds instead.

**Comment by kpad-git** [comment]
I'm also having this issue with Foundry 0.8.8 where everything worked perfectly in 0.7.x. I created an issue on the Midi project page, but there was a similar one from several months ago that is still open. It's too hard to turn off midi-qol for all the other great stuff it gives, but the sounds were very fun too :(

**Comment by eclarke12** [comment]
I'll look at patching for midiQOL if I can

**Comment by LionheadGaming** [comment]
I'm having the same issue but with Better Rolls 5E no midiQOL at all.

**Comment by kpad-git** [comment]
Tim Posney (the author of midi-qol) diagnosed this and opened an issue (https://github.com/death-save/maestro/issues/140). Fixing that issue should resolve this for midi and better rolls.

**Comment by eclarke12** [comment]
Refer to #140
