### ISSUE TITLE
doesn't pull random sounds, always the same ones

### ISSUE THREAD

**Issue by susscribe** [death-save/maestro#132]
latest update is working on latest dnd5e and latest stable foundry but doesn't pull a random track from a list, just the same one every time. tried having the list as "random" rather than "soundboard" and changed which track is played but still not random. (tried the other options too just to be sure)

1.  ##
![brave_lBeAofOeEV](https://user-images.githubusercontent.com/87147923/125543174-ec4841b1-a94e-4bb1-bba0-0180d17ef698.png)

2. 
![brave_6lT3KAgkcx](https://user-images.githubusercontent.com/87147923/125543247-7d8b8075-8fb0-4331-8988-72495ddefde7.png)

3. spammed rolls until nat 1 or 20 twice

Expected behavior
in 7.10 or older it used to pick a random track in the defined playlist.

 - OS: ubuntu
 - Browser Chrome,   ##Brave
 - Foundry Version 0.8.8
 - DnD5e system V 1.3.6
 - Maestro Version 0.7.5
 
thank you so much for updating it to latest stable fvtt!

**Comment by Nedrapter** [comment]
I'm having similar behavior with combat music. Whenever I select it to play a random track from a playlist it always plays the same.

**Comment by Bekradan** [comment]
Same issues here.

**Comment by eclarke12** [comment]
There's an issue with the sort functionality that Maestro is using to find the track. I assumed it hadn't changed from Foundry v7 to v8 but evidently it did. Will be fixed in the next release!

**Comment by susscribe** [comment]
nice! tysm!

**Comment by Bekradan** [comment]
Many thanks for letting me know. That is most kind of you. 

Kind regards,

Wayne
