### ISSUE TITLE
Item sound does not play for unlinked tokens (dnd5e)

### ISSUE THREAD

**Issue by High-123** [death-save/maestro#133]
**Describe the bug**

In the dnd5e system (1.3.6) with Maestro (0.7.5) as the only installed module, item tracks do not play for unlinked tokens.

**To Reproduce**

1. Enable the Maestro module and the "Enable Item Track" setting.
2. Create an actor.
3. Add a weapon from the items compendium (e.g. Greatsword)
4. Add an item track to said weapon
5. Test the attack roll of the weapon. _Here the item sound should play._
6. Edit the actor to be an unlinked actor by clicking on "Prototype Token" and unchecking "Link Actor Data".
7. Drag the unlinked actor to a scene.
8. Close all open actor sheets and open the actor sheet by double clicking the token. The actor sheet should now be called "[Token] Name of Actor"
9. Roll the weapon attack. Now no item sound will be played and an error will show up in the console.

**Expected behavior**

The item sound should also be played for unlinked tokens.

**Screenshots**

![image](https://user-images.githubusercontent.com/87529152/125944945-3778e591-288a-421c-907a-f3ea471b1836.png)
![image](https://user-images.githubusercontent.com/87529152/125944952-1e0f2f98-1a66-40e8-a669-5d34e02adf02.png)
![image](https://user-images.githubusercontent.com/87529152/125944960-cb810670-f530-4f04-b4d5-ad03f5147565.png)

**Foundry Setup (please complete the following information):**

 - OS: Windows
 - Browser Chrome
 - Foundry Version 0.8.8
 - Maestro Version 0.7.5

**Additional context**

It seems, that the disassembly of the scene and token ids in line 67 of the item-track.js fails and does not correctly extract the right ids.

`const [dummy1 , sceneId, dummy2, tokenId] = sceneTokenId.split(".");` as a replacement line seems to be a simple fix.

**Comment by 00zim00** [comment]
Since its listed as unconfirmed. Thought I would confirm the same behavior as listed in the issue post.
