### ISSUE TITLE
Add support for the Cyberpunk Red CORE system

### ISSUE THREAD

**Issue by High-123** [death-save/maestro#134]
**Is your feature request related to a problem? Please describe.**

The item track functionality does not work for unlinked tokens for the CPR Core system. For unlinked tokens in the CPR Core system, the `data-token-id` passed to the chat message actually only contains the token id instead of the uuid of the token. Thus one cannot disassemble the data into a scene and token id to get the item. Instead one can directly access the token by its id.

**Describe the solution you'd like**

An adjustment of the code in item-track.js to also accept the content of `data-token-id` to be the id of the token instead of the uuid of the token. This can for example be achieved by checking for a dot (`.`) inside the string and if it does not appear assume that it is the token id instead of the uuid, which would contain a dot. An example of how it could be implemented can be seen in the additional context.

**Describe alternatives you've considered**

An other alternative would be to ask the developers of the CPR Core system to change to using the uuid of the token instead of the id. This however would also require the uuid to work correctly for unlinked tokens, which is did not in my testing with the dnd5e system, which uses the uuid in that data point. (See issue #133)

**Additional context**

A suggestion for allowing compatibility for systems, which only use the token id instead of the uuid of the token in the data point `data-token-id` could be implemented in the following way.

File modules/item-track.js line 66 onwards:
```js
if (sceneTokenId) {
   if (sceneTokenId.includes(".")){
        // Original code, where there is the scene id and token id inside "data-token-id".
        const [sceneId, tokenId] = sceneTokenId.split("."); // This might still be wrong, see Issue 133
        const token = canvas.scene.id === sceneId ? canvas.tokens.get(tokenId) : game.scenes.get(sceneId)?.data.tokens.find(t => t._id === tokenId);
        item = token.actor.getOwnedItem(itemId);
    } else {
        // Case, there "data-token-id" only contains the token id.
        const token = game.actors.tokens[sceneTokenId].token;
        item = token.actor.getOwnedItem(itemId);
    }
}

```

**Comment by eclarke12** [comment]
Fixed in 0.7.6
