### ISSUE TITLE
Crit Success/Failure not triggering

### ISSUE THREAD

**Issue by bearfistingchampion** [death-save/maestro#139]
**Describe the bug**
I have maestro installed and it lets me create playlists and whatever I need but the dice portion does not work. It doesn't disable dice sounds and the success and fail sounds don't activate either.

**To Reproduce**
1. Go to 'Maestro configuration settings'
2. Click on 'click active the critical success and failures playlist and click disable dice sounds on table'
3. Load your playlist with sounds
4. Roll and the dice rolling sound still plays and no sound on crits

**Expected behavior**
On a crit it should choose a random track from the playlist attached to it and play it..

**Screenshots**
![Settings](https://user-images.githubusercontent.com/86370235/127891721-acea317b-addc-49cb-9643-6df4866a7a4a.PNG)

![More Settings](https://user-images.githubusercontent.com/86370235/127891730-1c151af8-7f2e-4246-8523-15c8c8f64046.PNG)

**Foundry Setup (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Foundry Version [0.8.8]
 - Maestro Version [0.7.5])

**Additional context**
This is the only module installed.

**Comment by eclarke12** [comment]
What game system? Any rolling modules being used?

**Comment by bearfistingchampion** [comment]
> What game system? Any dice/rolling modules being used?

Dnd 5e and absolutely no other mods

**Comment by eclarke12** [comment]
Can you please show me your playlists and some example rolls in chat that should've  triggered it? The last update revised the code to basically mirror what 5e does for highlighting so it *should* work!

**Comment by bearfistingchampion** [comment]
![playlist](https://user-images.githubusercontent.com/86370235/127929138-2185da64-28f1-46bf-85c5-1b653dcbbfa3.PNG)

![rolls](https://user-images.githubusercontent.com/86370235/127929163-676a4c15-e60c-488b-9065-398ce8c00747.PNG)

**Comment by bearfistingchampion** [comment]
as i said as well the default dice sounds are still playing as well when they shouldnt

**Comment by eclarke12** [comment]
I think the `kh` `kl` is messing it up. It's possible the logic isn't covering that scenario correctly.

**Comment by denro** [comment]
I've also tried to get the critical hit/miss to work on a new game without success. I've used the same settings as @bearfistingchampion to create the playlists and also tried to specify the individual tracks to play.

I first thought there was another module interfering so i created a clean world with only the maestro module enabled, still no success. I've tried multiple  browser, sound-files, playlist settings, ways of rolling dice but i'm not able to get the critical effects to play.

Combat tracks works as expected for start of combat.

Foundry Setup (please complete the following information):

OS: [Mac OS BigSur]
Browser [Firefox]
Foundry Version [0.8.8]
Maestro Version [0.7.5]

**Comment by denro** [comment]
Fortunately you can achieve the same outcome with the Dice so Nice plugin in Foundry, just add a special effect for 1 and 20 with the play custom file and enable it for all players

**Comment by eclarke12** [comment]
This is fixed in the upcoming release.
