### ISSUE TITLE
Item card "data-token-id" has changed format. When set this breaks maestro

### ISSUE THREAD

**Issue by tposney** [death-save/maestro#140]
**Describe the bug**
As of 0.8.x/dnd 1.4(? not really sure which version) the format of the item card field "data-token-id" has changed.
It used to be "SceneId.TokenId", it is now "Scene.SceneId.Token.TokenId" and is set in dnd5e displayCard to
```
tokenId: token?.uuid || null,
```
Midi-qol always sets it and dnd5e set's it for unlinked tokens.  
The code
```  const [sceneId, tokenId] = sceneTokenId.split(".");  ``` won't work with the new format.
``` [sceneTag, SceneId, tokenTag, tokenId]="Scene.xxx.Token.yyy".split(".")``` should work.
 
You can also replace all the sceneTokenId code with a one liner.
 ```
if (sceneTokenId) {
    item = await fromUuid(`${sceneTokenId}.Item.${itemId}`);
}
```

**To Reproduce**
Roll an item from an unlinked token.

**Foundry Setup (please complete the following information):**
 - OS: linux
 - Browser chrome
 - Foundry Version 0.8.8
 - Maestro Version 0.7,5

**Additional context**

**Comment by kpad-git** [comment]
This issue is preventing me from using Maestro without breaking combat automation... is Maestro still being supported?

**Comment by tposney** [comment]
For those who are struggling with this issue and pending a release of the module a workaround is to change lines 66 through 70 of Data/modules/maestro/moudles/item-track.js from
```
        if (sceneTokenId) {
            const [sceneId, tokenId] = sceneTokenId.split(".");
            const token = canvas.scene.id === sceneId ? canvas.tokens.get(tokenId) : game.scenes.get(sceneId)?.data.tokens.find(t => t._id === tokenId);
            item = token.actor.getOwnedItem(itemId);
        } else if (!sceneTokenId && actorId) {
```
to
```
        if (sceneTokenId) {
          item = await fromUuid(`${sceneTokenId}.Item.${itemId}`);
        } else if (!sceneTokenId && actorId) {
```
which should solve the problem

**Comment by kpad-git** [comment]
Hi tposney, thanks for your support! I tried the solution you gave but it didn't work for me. I am using midi-qol and "better rolls" in conjunction - the automation all works fine, auto damage application etc, but no item track sound coming out even though it is populated with the correct sound fine. Is there a particular setting in midi-qol that needs to be set a certain way for this to work?

**Comment by DrewStremer** [comment]
I have changed the lines and uploading the fixed file to my server, but the issue is persisting for me. Is there a specific Midi-QoL setting that I need to have checked? I am wondering if I am just having issues with the workflow settings themselves.

**Comment by franckflo** [comment]
I'm afraid Tim's suggested patch did not work for me either.

**Comment by eclarke12** [comment]
I have a fix in the next release. Out shortly.
