### ISSUE TITLE
Item Tracks don't play in Star Wars RPG

### ISSUE THREAD

**Issue by Xeohelios** [death-save/maestro#141]
**Describe the bug**
Item tracks do not play at all in the Star Wars RPG system. This persists if I disable every module other than Maestro. 

**To Reproduce**
1. Choose any actor
2. Click the item's icon in order to bring up the roll dialogue
3. Roll any dice

**Expected behavior**
I expect, in theory, for Maestro to play whatever sound effect I've selected.

**Screenshots**
Not sure these would help here.

**Foundry Setup (please complete the following information):**
 - OS: Win10
 - Foundry Version 0.8.8
 - Star Wars FFG Version 1.6
 - Maestro Version 0.7.5

**Comment by eclarke12** [comment]
This game system does not send an `item-id` in the chat message HTML.

Tracking progress in #143 instead.

**Comment by eclarke12** [comment]
Opened https://github.com/StarWarsFoundryVTT/StarWarsFFG/issues/970 on their tracker
