### ISSUE TITLE
Item Track - Random Track plays the same sound each time

### ISSUE THREAD

**Issue by Saucealicious** [death-save/maestro#142]
**Describe the bug**
The item tracks "Play Random Track" doesn't randomize. It only plays the first track. If playlist is put on shuffle it's possible for it to play another sound, but it will still always play the same one.

**To Reproduce**
1. Make a playlist and put some tracks in.
2. Go to specific item and click Item Track.
3. Choose said playlist and "Play Random Track".
4. When the item is activated from a sheet it only plays the same sound from the playlist.

**Expected behavior**
That it would randomly choose a track from the specified playlist and play it.

**Foundry Setup (please complete the following information):**
 - OS: Windows 10
 - Foundry Version 0.8.8
 - Maestro Version 0.7.5

**Additional context**
Noticed in my campaign world that has a bunch of other modules. Tested in a completely new world with only Maestro activated and it was the exact same behaviour.

**Comment by Regniwekim** [comment]
I'm having this same issue. Everything is the same as above, but I am on Foundry Version 0.8.9.

**Comment by Nedrapter** [comment]
Having the same, since the release of .8 foundry. Had reported it previously too.

**Comment by eclarke12** [comment]
This is fixed in the upcoming release.
