### ISSUE TITLE
Item track not playing when consumable item's quantity is only 1

### ISSUE THREAD

**Issue by Steelpipes** [death-save/maestro#145]
**Describe the bug**
When 'destroy on empty' is checked and have only 1 item, item track is not playing. When have more than 1 item it works fine.

**To Reproduce**
1. Set an item track to any consumable item
2. 'Destroy on Empty' option is on
3. The item's quantity is only 1
3. Use the item

**Expected behavior**
Item track plays

**Foundry Setup (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Foundry Version 0.8.9
 - Maestro Version 0.7.5

**Comment by eclarke12** [comment]
Confirmed this one. Very interesting bug. I suspect the deletion of the item is causing the item track info to be lost before it can be processed. I will try to get this in 0.7.6 but it might have to wait for 0.7.8
