### ISSUE TITLE
Combat Tracks Playlist stops after one track

### ISSUE THREAD

**Issue by LordOHelmet** [death-save/maestro#151]
**Describe the bug**
After combat starts, the Combat Tracks Playlist starts playing BUT stops after just one track.

**To Reproduce**
1. Start Combat and wait...

**Expected behavior**
Play the full playlist of Combat Tracks

**Screenshots**
Not applicable.

**Foundry Setup (please complete the following information):**
 - OS: Win10
 - Browser: latest chrome
 - Foundry Version  0.8.9
 - Maestro Version 0.7.6
 - Game System: GURPS 0.11.12
 - Hosted: via The Forge

**Comment by eclarke12** [comment]
What settings do you have in the Combat Tracks config for that encounter? Please provide a screenshot if possible.

**Comment by LordOHelmet** [comment]
![maestro](https://user-images.githubusercontent.com/80178910/144828034-d15e385c-8739-420c-aeb5-26915bc73bdc.JPG)

**Comment by eclarke12** [comment]
what does it show in the Combat Tracks config (click the music note button in the Combat Tracker)

**Comment by LordOHelmet** [comment]
Sorry, didn't notice that configuration option before!
But that solved my issue.

Had it set on ´Play Random Track´ before
![track](https://user-images.githubusercontent.com/80178910/145015512-12918a47-4502-470c-b32f-94eef54669cc.JPG)

Switched it to ´Play Playlist´
![list](https://user-images.githubusercontent.com/80178910/145015673-3ffff2e3-1d80-4e06-846a-fd2984bef81e.JPG)
Now it is working!

Thanks again!

**Comment by eclarke12** [comment]
The UI for Maestro is not the best in places. Sorry for the confusion, glad you got it resolved!
