### ISSUE TITLE
[BUG] Unable to pull up open item track tab on items.

### ISSUE THREAD

**Issue by Enderrrr** [death-save/maestro#16]
![image](https://user-images.githubusercontent.com/58924198/70875335-9d646280-1f83-11ea-97fa-776ca3372a06.png)

While i'm able to open and modify the item tracks on items that already have tracks assigned to them, attempting to open it on new items gives me this error. I am using the latest version of Maestro and Foundry.

**Comment by eclarke12** [comment]
@Enderrrr just confirming this is resolved?
