### ISSUE TITLE
[ENH] Soundboard 

### ISSUE THREAD

**Issue by BrotherSharper** [death-save/maestro#17]
A basic soundboard UI where the user can define the name, image, source and key combination for a specific sound effect.
The sound is later played by either clicking on the icon that appears on the soundboard or by pressing the key combination.

See the following site for an example
https://www.myinstants.com/categories/sound%20effects/

**Comment by anathemamask** [comment]
Add a volume mixer to this request and i'll weep with joy.

**Comment by eclarke12** [comment]
covered by a different module: https://foundryvtt.com/packages/SoundBoard/
