### ISSUE TITLE
[ENH] Allow trusted players to upload their own tracks/modify your playlist

### ISSUE THREAD

**Issue by BrotherSharper** [death-save/maestro#20]
Give full access to trusted players to see, edit and play your playlists just like a GM.

With enough trusted players you can improve your online experience by assigning someone to DJ duty.
This is a tried and tested method that is preferred by Japanese users due to it being a default option in one of their VTTs.

**Comment by renanmgs** [comment]
This! 
I just want to my players set the tracks of their own skills, i got 5 players lvl 7 with a ton of skills and its a lot of job to download, set on the folds, import, set in every skill all the tracks.

**Comment by eclarke12** [comment]
This is something to take up with Atropos as a core feature. With the new Player Permissions menu this should be easier to get implemented in core
