### ISSUE TITLE
[Bug] Hype Track: When turning the Hype Track setting on, tracks cannot be set until refresh

### ISSUE THREAD

**Issue by Rawrly85** [death-save/maestro#41]
When you enable the hype track via the settings, go to your actor and select the button, nothing happens and an error is given: 
hype-track.js:179 Uncaught (in promise) TypeError: Cannot read property 'sounds' of null
   at HypeTrackActorForm.getData (hype-track.js:179)
   at HypeTrackActorForm._render (foundry.js:3209)
   at HypeTrackActorForm.render (foundry.js:3183)
   at HypeTrack._openTrackForm (hype-track.js:147)
   at HTMLAnchorElement.<anonymous> (hype-track.js:132)

Even after adding the playlist, this issue can still exist. It currently requires a page refresh to get it to work.

**Comment by eclarke12** [comment]
NTS: issue likely caused by the Hype Tracks playlist not being created in a timely fashion, or the lack of a guard clause to prevent a lookup for a non-existent playlist

**Comment by eclarke12** [comment]
NTS: it was a typo.........................
