### ISSUE TITLE
Combat Tracks don't show up when using pf2e game system

### ISSUE THREAD

**Issue by eclarke12** [death-save/maestro#48]
Reported by llothos on discord

**Comment by llothos** [comment]
LLothos, i need me some final Fantasy 7 battle music.

**Comment by eclarke12** [comment]
@llothos this is caused by a change in the PF2e system. An upcoming update to the system should resolve the issue. See: https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/issues/510
