### ISSUE TITLE
Combat Track continues playing during Hype Track

### ISSUE THREAD

**Issue by MrPavao** [death-save/maestro#50]
The Combat Track continues to play when a Hype Track starts, resulting in a muddy train wreck.

Maybe stopping the Combat Track when a Hype Track starts and then starting it again as the Hype Track ends would create a de facto default NPC hype track?

Thanks for making this--it's awesome. And it gives new life to my mp3 collection. 🙂

**Comment by SpartanCPA** [comment]
👍 to this issue

**Comment by eclarke12** [comment]
this is doable but blocked by #57
