### ISSUE TITLE
Combat track overlaps with other ambience tracks

### ISSUE THREAD

**Issue by Wokeye** [death-save/maestro#69]
I've noticed the combat tracks overlap with existing music being played. Is there an automagical way to stop other tracks when the combat starts, perhaps a 'pause other playlist sounds when combat starts'?

**Comment by eclarke12** [comment]
Yes there is a way to do this, which I am now doing with Hype Tracks. I hope to extend this functionality to Combat Tracks in a future release!

**Comment by VampireNighthawk** [comment]
Any word on when this functionality could be expected?

**Comment by eclarke12** [comment]
> Any word on when this functionality could be expected?

Maestro needs to be rewritten in many parts to work with the new Foundry 08x audio subsystem. I hope to tackle this in the coming months, but no ETA for now.

**Comment by eclarke12** [comment]
This is implemented in the next release
