### ISSUE TITLE
Improve the detection of critical rolls

### ISSUE THREAD

**Issue by DeadlyArtist** [death-save/maestro#77]
EDIT: After another dozen times times I realized it only works for certain predefined things, like attacks and ability checks, but not custom dice roles. Really wished there were more options to customize that.

**Comment by nullpunktTUD** [comment]
I cannot seem to get the Crit Hit and Miss sounds to play in a Pathfinder 1 game. I have a bunch of modules active (of course), but I don't think anything that is changing the chat output (which I learned is what is used to trigger the sounds). This is what it looks like:

![image](https://user-images.githubusercontent.com/18614423/119253649-7ff0ea80-bbb2-11eb-860d-63cffd061e7c.png)

Am I missing anything?

**Comment by eclarke12** [comment]
> I cannot seem to get the Crit Hit and Miss sounds to play in a Pathfinder 1 game. I have a bunch of modules active (of course), but I don't think anything that is changing the chat output (which I learned is what is used to trigger the sounds). This is what it looks like:
> 
> ![image](https://user-images.githubusercontent.com/18614423/119253649-7ff0ea80-bbb2-11eb-860d-63cffd061e7c.png)
> 
> Am I missing anything?

because this feature was designed around an older version of the dnd5e dice roll, it may no longer work and compatibility with other game systems is not guaranteed. I will be looking at fixing the issue in the future, but for now check out the similar functionality in Dice so Nice or other dice mods.

**Comment by nullpunktTUD** [comment]
Thanks for the response!

I managed to get what I want from the Dice So Nice module.

**Comment by eclarke12** [comment]
Changes in 0.7.6 should bring this a bit closer to expectations with the ability to configure the die type (eg. d6, d20 etc) and critical success/failure thresholds.
