### ISSUE TITLE
Obsidian Support

### ISSUE THREAD

**Issue by NukeMaster0** [death-save/maestro#80]
I was wonder if there would ever be support for the module "Obsidian Character Sheets" as the option to insert a sound into an item is there, it just does not work no matter what sound file I use.

Link to the module-
https://bitbucket.org/Fyorl/obsidian/src/master/

![Capture](https://user-images.githubusercontent.com/68701755/91768205-481cbf80-ebab-11ea-9bb0-0375500a0daf.JPG)

**Comment by eclarke12** [comment]
The issue with Obsidian and other modules of that sort is the way they change the rolling workflow, which is what Item Track currently uses to trigger its sounds.

It is something I want to explore in the future.
