### ISSUE TITLE
Support Playlist or track for Hype tracks

### ISSUE THREAD

**Issue by JamzTheMan** [death-save/maestro#81]
I've built up a collection of NPC voice tracks from games like Neverwinter Nights, Baldur's Gate, DOTA, etc.  They usually all have several voice quotes to handle things like low health, being activated, attacking, casting, etc.  Usually I can pick anywhere from 6-20 items that all work well for "initiative" and adds variety vs saying the same thing over and over.

It's actually quite funny when they yell ATTACK! on turn 1 then RUN! or RETREAT! or such on turn 2. :) And since it's all the same voice, the PC still recognizes it's there turn (so I use Hype tracks more as a "hey, it's your turn" vs, well, "hype"

Granted, having a few AC/DC songs vs 1 for a Hype list vs track wouldn't be terrible either...

**Comment by davesturtevant** [comment]
Just came here to request the same thing: hype-playlists!
