### ISSUE TITLE
Issues using Maestro Crit Sounds

### ISSUE THREAD

**Issue by SugarSheikh** [death-save/maestro#84]
Hi,

New to foundry ant was excited to use Maestro since I had a similar API in Roll20. However, after setup, the crit sounds don't play automatically. 

When I navigate to a playlist, I can play the sounds on demand; but after testing the rolls, they don't activate on a crit success or fail.

Taking a look in the console, I thought that [this ](https://gyazo.com/ba33d47687ec1f69358a52cc4d8a9c0d) may have had something to do with it, but I'm not sure. 

Any help would be appreciated, thanks!

Edit: I should mention I'm using forge VTT to host.

**Comment by Bryn1701** [comment]
I too am having trouble with the crit success and fail section of Maestro. The rest works fine. I have tested it both local and on The Forge and I get the same result, no sound playing.

**Comment by eclarke12** [comment]
This is probably caused because the logic for crit sounds is very narrowly focused on using the same logic as the dnd5e system. So if a roll fails to meet those criteria, it will not trigger the sound.

This will be fixed in a future update.

**Comment by SugarSheikh** [comment]
Hi Again, thanks for the response

Currently, I'm using the 5e system, but also a number of modules such as Better Rolls or Private Rolls. As I'm understanding, this is what may be causing the issue?

If so, is there anything I could pass over to you that might help?

Many Thanks,

**Comment by eclarke12** [comment]
Sorry I didn't explain myself very well. Both BR and PR change the roll chat message, which is what Maestro is looking at. So unfortunately that causes this functionality to fail.

There is definitely room for improvement here that I will address in a future update!

**Comment by SugarSheikh** [comment]
Got it! Thanks for explaining 👍

**Comment by eclarke12** [comment]
closing as i will capture this in #77
