### ISSUE TITLE
Character Hype Tracks activating during Initiative rolls

### ISSUE THREAD

**Issue by Arcyl** [death-save/maestro#86]
I am having an issue where Hype Tracks are activating on initiative rolls in the combat tracker. More specifically whichever actor comes first in the list alphabetically seems to then cause every initiative roll to activate that actor's hype track. So Actor 'A' is first in the list of the combat tracker, any initiative roll in the combat tracker will activate Actor 'A's Hype Track. If Actor 'A' has no hype track then initiative rolls act normally with no hype tracks.

I would rather hype tracks not activate at all in the combat tracker, and definitely not the same one again and again. 

Here is a video showing the issue. 
https://drive.google.com/file/d/1RoIGeEV05x4BGkCXAkpMwV5UsdHQczok/view?usp=sharing

I'm really enjoying this module otherwise, thank you.

**Comment by eclarke12** [comment]
Thanks for this @Arcyl, when the turn order changes it triggers the functionality that Maestro uses to play a Hype Track. I hope to refine this logic in a future update.
