### ISSUE TITLE
Combat Track UI non-functional in .75

### ISSUE THREAD

**Issue by Lazytron** [death-save/maestro#90]
**Describe the bug**
Combat Track UI only accepts clicks on "Save" and "Close" buttons, meaning tracks cannot be set or updated for combats.

**To Reproduce**
1.) Create a combat as GM
2.) Open combat track settings
3.) Observe "DEFAULTS" and  "Encounter" headers
4.) be sad they cannot be accessed (click has no behavior) 

**Expected behavior**
Settings should render for "DEFAULTS" on open, allow switching betweeen "DEFAULTS" and "Encounter" tab for relevant settings.

**Screenshots**
https://media.discordapp.net/attachments/672923389681336351/768967806825267251/unknown.png

**Foundry Setup (please complete the following information):**
 - OS: Win10 local, server on Forge
 - Browser [Chrome, Firefox]
 - Foundry Version [0.7.5]
 - Maestro Version [ 0.7.1]

**Additional context**
No console errors

**Comment by KirikTheOrc** [comment]
Can confirm this bug, as I am experiencing it myself as well with the same settings. It can't be changed and clicking on the settings for it does nothing for me.

**Comment by eclarke12** [comment]
This bug is confirmed and I am committed to fixing it, but currently I'm
focusing on some issues in CUB. I hope to have a Maestro patch by this
time next week.
