### ISSUE TITLE
Lots of lag when changing track

### ISSUE THREAD

**Issue by Avitale34** [death-save/maestro#92]
**Describe the bug**
When you have Maestro enabled and the tracks change there is a large lag spike that brings the game to a halt for 15-20 seconds. With the module uninstalled it works fine no lag spikes when changing song.

**To Reproduce**
1. Have multiple sources connected to your game
2. Play a track and wait for it to change
3. Experience lag spike

**Expected behavior**
It used to change songs fine before 7.5

**Comment by eclarke12** [comment]
Hi @avitale34, can you confirm when you say "play a track" you mean a
standard Playlist Track from the built in Foundry Playlist functionality?

**Comment by Avitale34** [comment]
Yea just standard playlist function.

**Comment by eclarke12** [comment]
Fixed in #96
